In [1]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [9]:
mytensor = torch.rand(2,3,4)
print(mytensor)

tensor([[[0.7257, 0.0375, 0.3928, 0.6811],
         [0.6923, 0.8628, 0.1431, 0.6272],
         [0.9382, 0.0817, 0.0229, 0.1929]],

        [[0.9197, 0.0387, 0.9601, 0.3296],
         [0.5874, 0.7466, 0.8387, 0.7971],
         [0.4456, 0.6115, 0.2038, 0.9988]]])


In [12]:
x0 = torch.tensor(1., requires_grad=True)
x1 = [1]
print(x0)
print(x0.grad)

tensor(1., requires_grad=True)
None


In [14]:
# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()
# Print out the gradients.

print(x)
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 



tensor(1., requires_grad=True)
tensor(2.)
tensor(1.)
tensor(1.)


In [15]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)



w:  Parameter containing:
tensor([[0.1799, 0.2461, 0.3176],
        [0.4460, 0.1929, 0.0145]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.4867, -0.5004], requires_grad=True)


In [16]:
# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

# 1-step gradient descent.
optimizer.step()

# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss:  1.2608823776245117
dL/dw:  tensor([[ 0.2990, -0.4332,  0.0668],
        [ 0.5176,  0.0865,  0.2857]])
dL/db:  tensor([ 0.3483, -0.6068])
loss after 1 step optimization:  1.249678134918213


In [17]:
# Download and construct CIFAR-10 dataset.
train_dataset = torchvision.datasets.CIFAR10(root='/home/fogman/my-venv/data',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)

# Fetch one data pair (read data from disk).
image, label = train_dataset[0]
print (image.size())
print (label)

# Data loader (this provides queues and threads in a very simple way).
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64, 
                                           shuffle=True)

# When iteration starts, queue and thread start to load data from files.
data_iter = iter(train_loader)

# Mini-batch images and labels.
images, labels = data_iter.__next__()

# Actual usage of the data loader is as below.
for images, labels in train_loader:
    # Training code should be written here.
    pass


torch.Size([3, 32, 32])
6
